#!/bin/bash
SCRIPT_HOME=`cd $(dirname $BASH_SOURCE) && pwd`  # get SCRIPT_HOME=executed script's path, containing folder, cd & pwd to get container path
   APP_HOME=`cd "$SCRIPT_HOME/../.." && pwd`
   DOCKER=`cd "$SCRIPT_HOME/.." && pwd`


docker build --build-arg ENV_TAG=UAT   -f $DOCKER_HOME/Dockerfile   -t trangtruong1610/docker-action   $APP_HOME
#            TODO trang always UAT?    Dockerfile path              docker image tag                   source path
