#!/bin/bash
SCRIPT_HOME=`cd $(dirname $BASH_SOURCE) && pwd`  # get SCRIPT_HOME=executed script's path, containing folder, cd & pwd to get container path
   APP_HOME=`cd "$SCRIPT_HOME/../.." && pwd`
DOCKER_HOME=`cd "$SCRIPT_HOME/.." && pwd`

    # get git commit id
    gitcommitid=`git describe --always`

    # get ENV_TAG from .env.UAT
    source $DOCKER_HOME/config_vault/.env.UAT

    docker build   --build-arg ENV_TAG=$ENV_TAG   --build-arg GIT_COMMIT_ID=$gitcommitid   -f $DOCKER_HOME/Dockerfile   -t trangtruong1610/docker-action:$ENV_TAG   $APP_HOME
    #              buildtime param ENV_TAG          buildtime param GIT_COMMIT_ID             Dockerfile path              image tag                                source folder
